# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: tetraweb/php

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install -y gettext-base
  - npm install -g npm@latest
  - npm install -g grunt-cli --save-dev

stages:
  - makepot

cache:
  paths:
    - node_modules/

makepot_create:
 stage: makepot
 only:
  - master
 script:
  - npm install
  - grunt makepot
  - grunt push --user=$ZANATA_USER --token=$ZANATA_TOKEN
 artifacts:
  paths:
   - languages/
